// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMmQpjKxAxbibg32bry7kttYFfTXXibQ',
    appId: '1:485605032271:web:541bd3946a85e230a6453a',
    messagingSenderId: '485605032271',
    projectId: 'fruit-hub-e-commerce-app',
    authDomain: 'fruit-hub-e-commerce-app.firebaseapp.com',
    storageBucket: 'fruit-hub-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATBv9Qp6G_-sxeiMA3axnA1XLCPxwT6nI',
    appId: '1:485605032271:android:b7fa2aeaa7f038f4a6453a',
    messagingSenderId: '485605032271',
    projectId: 'fruit-hub-e-commerce-app',
    storageBucket: 'fruit-hub-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcEDGdovS1ppjHiGR3kH5NfSa-d1ntlsQ',
    appId: '1:485605032271:ios:585da42be850da40a6453a',
    messagingSenderId: '485605032271',
    projectId: 'fruit-hub-e-commerce-app',
    storageBucket: 'fruit-hub-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcEDGdovS1ppjHiGR3kH5NfSa-d1ntlsQ',
    appId: '1:485605032271:ios:585da42be850da40a6453a',
    messagingSenderId: '485605032271',
    projectId: 'fruit-hub-e-commerce-app',
    storageBucket: 'fruit-hub-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitHubECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqMmQpjKxAxbibg32bry7kttYFfTXXibQ',
    appId: '1:485605032271:web:a68648eb4d674894a6453a',
    messagingSenderId: '485605032271',
    projectId: 'fruit-hub-e-commerce-app',
    authDomain: 'fruit-hub-e-commerce-app.firebaseapp.com',
    storageBucket: 'fruit-hub-e-commerce-app.firebasestorage.app',
  );
}
